# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  Bapi-Buildpools
stages:
  - stage: Build
    jobs:
      -  job: Buildjob
         steps:
            - task: Docker@2
              inputs:
               containerRegistry: 'aks-acr-svc'
               repository: 'Customaksnginxapp'
               command: 'buildAndPush'
               Dockerfile: '**/Dockerfile'
            - task: CopyFiles@2
              inputs:
                SourceFolder: '$(build.Sourcesdirectory)'
                Contents: '**'
                TargetFolder: '$(build.artifactstagingdirectory)'
                OverWrite: true
            - task: PublishBuildArtifacts@1
              inputs:
                PathtoPublish: '$(Build.ArtifactStagingDirectory)'
                ArtifactName: 'drop'
                publishLocation: 'Container'
            - task: DownloadBuildArtifacts@1
              inputs:
                buildType: 'current'
                downloadType: 'single'
                artifactName: 'drop'
                downloadPath: '$(System.ArtifactsDirectory)'

